discord-link: "discord.gg/CHANGE_THIS"
website-link: "https://example.com"
passive-monster-spawning: false
rules:
  - name: Rule A
    description: A great rule
  - name: Rule B
    description: Another great rule