name: YAGPPPCore
version: '{ver}'
main: me.brandgrandreal.yagpppcore.YAGPPPCore
api-version: '1.21'
authors: [ BrandGrandReal ]
description: YAGPPP Core plugin

commands:
  discord:
    description: Get our discord link! :)
