# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Gradle Package

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Get release version
      id: get_version
      run: echo "::set-output name=VERSION::${{ github.event.release.tag_name }}"

    - name: Change {ver}
      uses: jacobtomlinson/gha-find-replace@v3
      with:
        include: src/main/resources/plugin.yml
        find: '{ver}'
        replace: ${{ steps.get_version.outputs.VERSION }}
        regex: false

    - name: Change {{user}}
      uses: jacobtomlinson/gha-find-replace@v3
      with:
        include: src/main/resources/plugin.yml
        find: '{{user}}'
        replace: ${{ github.actor }}
        regex: false

    - name: Change {{key}}
      uses: jacobtomlinson/gha-find-replace@v3
      with:
        include: src/main/resources/plugin.yml
        find: '{{key}}'
        replace: ${{ secrets.GITHUB_TOKEN }}
        regex: false


    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    - name: Build with Gradle
      run: ./gradlew build

    - name: Upload Artifact To Release
      uses: Shopify/upload-to-release@v2.0.0
      with:
        name: yagvcore.jar
        path: build/libs/*.jar
        repo-token: ${{ secrets.GITHUB_TOKEN }}